// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADCDOHT5kX1MpF8397woUJMSVcBDrFCAU',
    appId: '1:682431626582:android:dc38369541950ca81ceaf7',
    messagingSenderId: '682431626582',
    projectId: 'my-colorpick-flutter-project',
    storageBucket: 'my-colorpick-flutter-project.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFWWj1NLRlevVPhZQblaRTE-45xkdUiy0',
    appId: '1:682431626582:ios:94c3dee0abfe90891ceaf7',
    messagingSenderId: '682431626582',
    projectId: 'my-colorpick-flutter-project',
    storageBucket: 'my-colorpick-flutter-project.firebasestorage.app',
    iosBundleId: 'com.example.colorPicker',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFWWj1NLRlevVPhZQblaRTE-45xkdUiy0',
    appId: '1:682431626582:ios:94c3dee0abfe90891ceaf7',
    messagingSenderId: '682431626582',
    projectId: 'my-colorpick-flutter-project',
    storageBucket: 'my-colorpick-flutter-project.firebasestorage.app',
    iosBundleId: 'com.example.colorPicker',
  );

}